"""Zero-shot runtime orchestrator."""

from __future__ import annotations

from typing import Any, Dict, List

import pandas as pd

from taxomind.pipelines.zero_shot import nodes as zero_shot_nodes
from taxomind.utils import embedding_utils, taxonomy_utils


class ZeroShotRunner:
    """Expose top-down routing, validation, and judge orchestration."""

    def __init__(self, model_name: str, judge_model_name: str) -> None:
        self._taxonomy: pd.DataFrame | None = None
        self.model_name = model_name
        self.judge_model_name = judge_model_name

    def load_taxonomy(self, taxonomy: pd.DataFrame) -> None:
        if "enriched_text" not in taxonomy.columns:
            taxonomy["enriched_text"] = taxonomy.apply(
                taxonomy_utils.compose_text, axis=1
            )
        if "embedding" not in taxonomy.columns:
            raise ValueError(
                "taxonomy must include multilingual embeddings generated by the embedding pipeline"
            )
        self._taxonomy = taxonomy

    def classify(self, text: str, metadata: Dict[str, Any] | None = None) -> Dict[str, Any]:
        if self._taxonomy is None:
            raise ValueError("Taxonomy is not loaded")

        embedding = embedding_utils.embed_texts(
            [text], model_name=self.model_name
        )[0]
        topdown = zero_shot_nodes.top_down_route(
            input_embedding=embedding,
            taxonomy_embedded=self._taxonomy,
        )
        bottomup = zero_shot_nodes.bottom_up_route(
            input_embedding=embedding,
            taxonomy_embedded=self._taxonomy,
        )
        topdown_route_for_match = [
            {"code": node.get("nodeCode")}
            for node in topdown.get("best_route", [])
            if node.get("nodeCode")
        ]
        bottomup_route_for_match = [
            {"code": node.get("nodeCode")}
            for node in bottomup.get("best_route", [])
            if node.get("nodeCode")
        ]
        routes_match = taxonomy_utils.routes_match(
            topdown_route_for_match, bottomup_route_for_match
        )
        bottomup_candidates: List[Dict[str, Any]] = []
        for entry in bottomup.get("topk", []):
            leaf = entry.get("leaf")
            if not leaf:
                continue
            candidate = dict(leaf)
            if "score" not in candidate:
                candidate["score"] = float(entry.get("score", 0.0))
            bottomup_candidates.append(candidate)
        resolved = zero_shot_nodes.judge_resolution(
            text,
            {
                "scores": bottomup_candidates,
                "route": bottomup.get("best_route", []),
                "routes_match": routes_match,
            },
            self._taxonomy,
            judge_model_name=self.judge_model_name,
        )

        return {
            "text": text,
            "metadata": metadata or {},
            "route": topdown.get("best_route", []),
            "validated": routes_match,
            "decision": resolved["judge_decision"],
        }
